// AUTO-GENERATED by scripts/build-post.mjs — do not edit by hand.
export interface BlogPostMeta {
  slug: string
  title: string
  description: string
  pubDate: string
  lang: 'en' | 'ru'
}

export const blogPosts: BlogPostMeta[] = []
